### ISSUE TITLE
I would like to translate this mod to Traditional Chinese, but I don't know how

### ISSUE THREAD

**Issue by TheIama** [segabl/pd2-warframe-hud#1]
I don't know how to translate it, because I want to fix this mod in-game chinese bug(everything will be like ___)
bad at talk english, sorry
![unknown](https://user-images.githubusercontent.com/98481874/151215736-416d3b4e-de15-4df4-a95b-dc1d6ccd65e4.png)
BTW, this mod is the best mod I ever seen

**Comment by segabl** [comment]
Hi, I have to look into that since the font I used doesnt contain any chinese letters. You can translate it by making a copy of english.txt and changing the text.

**Comment by segabl** [comment]
Hey, I just released an update which should now use the default fonts if the game is set to chinese

**Comment by TheIama** [comment]
OMG, thank you so mach!
