### ISSUE TITLE
detection risk to big

### ISSUE THREAD

**Issue by akramjh101** [segabl/pd2-warframe-hud#14]
detection risk to big on my screen

**Comment by segabl** [comment]
Can  you show a screenshot of what you mean?

**Comment by akramjh101** [comment]
whait

**Comment by akramjh101** [comment]
my steam error my be tomorow?

**Comment by akramjh101** [comment]
ehhh went aim screenshot the detection risk, detection risk is small but on the game ia big like1/10

**Comment by akramjh101** [comment]
aim cant show the screenshot sorry but is big like 1/10 of my screen
