### ISSUE TITLE
HUD recognised by SuperBLT but not showing

### ISSUE THREAD

**Issue by Vinc3Tsoi** [segabl/pd2-warframe-hud#16]
I've put the unzipped folder of Warframe HUD under mods folder created by SuperBLT. Warframe HUD is also recognised by SuperBLT and no updates are needed. However, when I get into a game, Warframe HUD is not showing.

I've tried with WolfHUD and WolfHUD works just fine. Is there anything I can do to fix this? Thanks a lot.

**Comment by segabl** [comment]
Did you get HopLib?

**Comment by Vinc3Tsoi** [comment]
Ah I didn't, and now the HUD works when I got it. 

Thanks, the HUD looks amazing
