### ISSUE TITLE
HUD does not respect subtitle settings

### ISSUE THREAD

**Issue by lnx00** [segabl/pd2-warframe-hud#23]
The HUD doesn't seem to respect the game's subtitle settings.
When i disable the subtitles in the game's options, they're still visible in-game.

**Comment by segabl** [comment]
Hm, this is an old issue that should have been fixed now last I checked. does it still happen when you enter the heist with subtitles already disabled?

**Comment by lnx00** [comment]
Yes, it still happens when I enter the heist with disabled subtitles.
I also made sure that this isn't caused by Vanilla HUD, which I had installed too.

**Comment by segabl** [comment]
to clarify, does it show the vanilla subtitles or the HUD's?

**Comment by lnx00** [comment]
It does show the vanilla subtitles at the bottom center. Sorry for not clarifying, i didn't know that the HUD usually contains it's own subtitle layout.

**Comment by segabl** [comment]
Ah okay I see why that might be happening. Should probably fixed with this update

**Comment by lnx00** [comment]
Yes, it's fixed now. Thank you very much for your efforts!
