### ISSUE TITLE
HUD doesn't show custom teammate interaction text + weird hexagon in the top left corner of the screen

### ISSUE THREAD

**Issue by CoaLMaN122PL** [segabl/pd2-warframe-hud#24]
The hud doesn't show custom teammate interaction text, only the vanilla one (Tested with VanillaPlus hud turned off and on)
![obraz](https://user-images.githubusercontent.com/51474134/187379171-89c4784b-5738-4288-be49-f3f2a4bcbbed.png)
and a weird olive hexagon appears and dissapears when you add and remove custom waypoints with "goonmod's custom waypoints" mod in the top left corner of the screen when you turn on the custom waypoint icons option
![obraz](https://user-images.githubusercontent.com/51474134/187379405-a5ff1132-8da5-4e78-a281-12a43b39cef8.png)
It also flashes for a split second "16:5" to the right of the hexagon when you add a custom waypoint no matter where you point and it also changes color to a white hexagon when you can escape

**Comment by segabl** [comment]
This seems like a HUD incompatibility, the hexagon is supposed to be the background of the waypoint marker. As for interaction text, that is currently not a thing in Warframe HUD and I'm still looking for a way to add it in a way that makes sense. Do you have any other HUD related mods? I've seen the waypoints break when some HUd scaling mod was used.

**Comment by CoaLMaN122PL** [comment]
Oh, sorry, i really thought it was there before. And for any other HUD related mods, the only one i could think of is better assault indicator, i can post my whole modlist if you want. I also found another problem, when someone joins mid-heist, you can still see their vanilla font name and their WF HUD font name at the same time, not sure if that is also related to a hud incompatibility, i could post my whole modlist if you want
![obraz](https://user-images.githubusercontent.com/51474134/187434403-2e36df3e-2729-494b-a5ec-dff6e86b5c6e.png)

**Comment by segabl** [comment]
Yeah your mod list would help since this doesn't happen on my end

**Comment by CoaLMaN122PL** [comment]
Here:
`SuperBLT, [Election Day Day 1] Truck Helper, Anti Blackscreen, Anti Stop The Cheater, BeardLib, BeardLib Editor, Better Assault Indicator,
 Better Bots, Big Oil Day 2 Stealth, blacklist heists from crime.net, Borderless Windowed Updated, Bullet Storm Trigger, Celer,
counterfeit stealth, Crime.NET Enhanced, Custom No Mercy Stealth, CustomFOV_Fixed, Drag and Drop Inventory, Drill Dig in,
Everything Meth, Fix Potential Experience, Force Host Pre-planning Choice, Full Offline Chat, Full Speed Swarm, Goonmod Shop  Standalone, GoonMod's Custom Waypoints, Iter, Keepers, Load Steam Inventory Once, Make BigOil Great Again, Map-Based Optimizations, Monkeepers, More Weapon Stats, MoreAFK, Music Control, No Concussion Tinnitus, No Duplicated Bullets, No Fade to black, No Loud Cleaner Costs, No Pager On Domination, No Prints, No Screen Shake 2.0, hoplib, Preplanning Manager Fixed, Radial Menu Vocalizer, reconnect to server, reLUA, Responsive Responders, RNGModifier, Saw Helper, Simple Mod, Stay there, Bile!!! [Counterfeit], Updater, STI Interaction + Mask Version, The Fixes, VanillaHUD Plus, Warframe Hud, XP Briefings`

**Comment by segabl** [comment]
Hmm not seeing anything other than vanillahud that could cause this. does it still happen without vanillahuf plus?

**Comment by CoaLMaN122PL** [comment]
When i restarted the game with vanillahud disabled, and played some heists the vanilla nametags didn't appear once, and when i enabled vanillahud and restarted it, they appeared on the very first heist i joined, so i think vanillahud might have something to do with it, and the waypoint was still sitting in the top left corner with vanillahud disabled

**Comment by segabl** [comment]
Hmm, I've seen other people use vanillahud with warframehud without issues. if you're using it for the inforboxes, might try using the infoboxes standalone mod instead. or see if there are some settings related to name labels in vhud plus.
not sure about the waypoint issue still, the only other hud related thing I see in your modlist is crime net enhanced but that shouldnt mess with ingame UI.

**Comment by CoaLMaN122PL** [comment]
I think i found the culprit of the custom waypoint being stuck in top left, it was for some reason Full Speed Swarm.

**Comment by segabl** [comment]
oh that is weird, it does indeed change the waypoint and name label functions for whatever reason

**Comment by segabl** [comment]
this should be fixed in 8830b280c6c6607e520c50953c4b8b88fcd26995
