### ISSUE TITLE
Extraordinarily high damage numbers

### ISSUE THREAD

**Issue by lnx00** [segabl/pd2-warframe-hud#25]
The damage popup is sometimes **waaay** to high. It seems that this only happens on headshots at the final hit. Maybe there's some kind of overflow while calculating the damage?

I'm using Warframe HUD with Vanilla HUD Plus in case that's significant. But i've made sure that every damage-related option is disabled in the latter.

![](https://i.imgur.com/ay9OBHe.png)

**Comment by segabl** [comment]
yeah I'm aware of this, not sure why it is happening and it's currently not high priority as it's not that common (also funny sidenote, this happens in Warframe randomly too, so consider it an easter egg for now 😛). Will keep this open to remind me to look into it however.

**Comment by lnx00** [comment]
> also funny sidenote, this happens in Warframe randomly too, so consider it an easter egg for now

Good old "It's not a bug, it's a feature" ;)
