### ISSUE TITLE
Doesn't seem to work (doesnt load)

### ISSUE THREAD

**Issue by bWildcard** [segabl/pd2-warframe-hud#35]
So i cant get this to load 

is it supposed to go into \SteamLibrary\steamapps\common\PAYDAY 2\assets\mod_overrides\Warframe Hud

I renamed pd2-warframe-hud-master to Warframe Hud 

Also if i go into opitions/advanced/mods/Warframe hud
no files are shown/listed
unlike other mods
same thing happens with the original older name

**Comment by segabl** [comment]
No, it's supposed to go into the mods folder and it also requires HopLib

**Comment by bWildcard** [comment]
yeah was missing hoplib thanks man
you might just include hoplib with your mods so idiots like me can avoid this issue ;) 

also is there any way to extended the info panel for team mates it currently doesn't give alot of info on them say like Void UI does

**Comment by segabl** [comment]
it's listed on the mod page as dependency and BLT should also prompt you to download it if you don't have it. what teammate information are you missing? some stuff isn't displayed by design.
