### ISSUE TITLE
i want adding korean translate

### ISSUE THREAD

**Issue by 8bitsein** [segabl/pd2-warframe-hud#4]
can you add korean translation of warframe hud? Translation is complete, where should I send it?

**Comment by DoctorKoKoDaYo** [comment]
just create a Pull requests with your translate and author will see it

**Comment by segabl** [comment]
> can you add korean translation of warframe hud? Translation is complete, where should I send it?

if you're familiar with how github pull requests work, you can fork this repository, add the translation to your copy and then create a pull request, but you can also send me the file on discord
