### ISSUE TITLE
I think Boss's health bar need a standalone settings for its font, place and size

### ISSUE THREAD

**Issue by DoctorKoKoDaYo** [segabl/pd2-warframe-hud#6]
![20220327001450_1](https://user-images.githubusercontent.com/67793712/160248915-07a0aa6c-875a-48c0-9727-d35ac48df889.jpg)

**Comment by DoctorKoKoDaYo** [comment]
![20220327095121_1](https://user-images.githubusercontent.com/67793712/160263365-6db02112-4f91-4c17-a909-787dd95636dd.jpg)
Yu Fu Wang's name is a total mess T_T

**Comment by segabl** [comment]
yes, I should probably not move the letters close together when not using the custom font

**Comment by segabl** [comment]
Should be fixed in e3dc2f1c4e27adabd7e37f40bf44849d229c76c8
