### ISSUE TITLE
Some strange "_" in text

### ISSUE THREAD

**Issue by DoctorKoKoDaYo** [segabl/pd2-warframe-hud#7]
![20220327093952_1](https://user-images.githubusercontent.com/67793712/160263409-aac0fbfc-f1fb-43d8-aafb-816b43365f2b.jpg)
As screenshot's chat window, after timestamps and colon always has a "_" .

**Comment by DoctorKoKoDaYo** [comment]
![image](https://user-images.githubusercontent.com/67793712/160263533-6a7f70c0-e629-4aa5-8481-1badccfdf1ae.png)

**Comment by segabl** [comment]
hm, I can see the cause for it in the chat, not sure why it happens in the subtitles, that would probably happen in vanilla too for them.

**Comment by segabl** [comment]
The chat one should be fixed in e3dc2f1c4e27adabd7e37f40bf44849d229c76c8

**Comment by DoctorKoKoDaYo** [comment]
> The chat one should be fixed in [e3dc2f1](https://github.com/segabl/pd2-warframe-hud/commit/e3dc2f1c4e27adabd7e37f40bf44849d229c76c8)
I updated to ver1.6.0,but chat one still has the problem
![image](https://user-images.githubusercontent.com/67793712/160287267-62c3513d-b90b-4405-acf9-cccfe69b8ebf.png)

**Comment by segabl** [comment]
I have not pushed out an official update for it yet, if you want to check it you need to manually download the dev branch from this repository

**Comment by DoctorKoKoDaYo** [comment]
![image](https://user-images.githubusercontent.com/67793712/160430748-3e0fc89d-14de-400a-9a2d-c648f173b919.png)
Yes, it fixed, but hud full of blue&yellow background

**Comment by segabl** [comment]
hm that's weird, make sure you're not running both versions
